config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "welcome#index"

  get 'about/index', to: 'about#index', as: 'about'

  resources :books, only: [:show, :index, :new, :create]
  resources :libraries, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :library_books
  has_many :libraries, through: :library_books
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_books
  has_many :books, through: :library_books

  before_validation :update_coordinates
  validates :name, presence: true, length: { maximum: 100 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :city, presence: true, length: { maximum: 50 }
  validates :state, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  def full_address
    "#{address}, #{city}, #{state} #{zip_code}"
  end

  def num_of_books
    books.count
  end

  def update_coordinates
    service = GoogleMapsService.new(full_address)
    coordinates = service.get_coordinates
    
    if coordinates.nil?
      puts 'Could not fetch coordinates.'
    else
      self.latitude = coordinates[:lat]
      self.longitude = coordinates[:lng]
    end
  end
end

app/models/library_book.rb
class LibraryBook < ApplicationRecord

  belongs_to :book
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @library = Library.find(params[:library_id])
  end

  def create
    facade = GoogleBooksFacade.new(params[:book][:isbn])
    if facade.book_details.nil?
      flash[:error] = "Book not found"
      redirect_to new_book_path(params[:book][:library_id])
    else
      book = Book.new(facade.book_details)
      book.save
      LibraryBook.create(library_id: params[:book][:library_id], book_id: book.id)
      redirect_to library_path(params[:book][:library_id])
      flash[:success] = "Book added to library"
    end
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def show
    @library = Library.find(params[:id])
  end

  def new
    @library = Library.new
  end

  def create
    library = Library.new(library_params)

    if library.save
      redirect_to library
    else
      determine_error_message(library)
      redirect_to new_library_path
    end
  end

  private

  def determine_error_message(library)
    if library.errors.full_messages.include?("Longitude can't be blank")
      flash[:error] = "Something about the address you entered is not valid. Please make sure the info you are providing is correct and try again.."
    else
      flash[:error] = "#{library.errors.full_messages.to_sentence}"
    end
  end

  def library_params
    params.require(:library).permit(:name, :address, :city, :state, :zip_code)
  end
end

app/controllers/library_books_controller.rb
class LibraryBooksController < ApplicationController
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def state_options
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/about/index.html.erb
<main class="about">
    <h1>About</h1>
    <%= render partial: "welcome/welcome_description" %>
</main>

app/views/books/_book_details.html.erb
<div class="book_details">
  <div class="book_cover_image">
  <img src="<%= @book.thumbnail_img %>">
  </div>
  <div class="book_details_title">
    <%= @book.title %>
  </div>
  <div class="book_details_author">
    Author: <%= @book.author %>
  </div>
  <% if @book.genre.present? %>
    <div class="book_details_genre">
      Genre: <%= @book.genre %>
    </div>
  <% end %>
  <% if @book.description.present? %>
    <div class="book_details_description">
      Description:
      <p><%= @book.description %></p>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<main class="container">
  Soon, you'll be able to search for books here!
  <div class="books">
    <% @books.each do |book| %>
        <%= link_to book_path(book) do %>
          <div class="book">
            <h2><%= book.title %></h2>
            <p>By: <%= book.author %></p>
          </div>
        <% end %>
    <% end %>
  </div>
</main>

<!--
<input type="file" accept="image/*" capture="camera" id="cameraInput">
-->

app/views/books/new.html.erb
<main class="container">
  <h1>Add a Book</h1>
  <div class="book_form">
    <%= form_with(model: @book, local: true) do |f| %>
      <%= f.hidden_field :library_id, value: @library.id %>
      <div class="field">
        <%= f.label :isbn %> (10 or 13):
        <%= f.text_field :isbn, placeholder: "1234567890" %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Add Book", class: "btn btn--submit" %>
      </div>
    <% end %>
  </div>
</main>

app/views/books/show.html.erb
<main class="container">
  <%= render partial: "books/book_details" %>
</main>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__name">
      Hello, &nbsp;<%= current_user.first_name %>!
    </div>
    <div class="navbar__title">
      <%= link_to image_tag("/bookhaven_logo.png", alt: "bookhaven"), root_path %>
    </div>
    <div class="navbar__actions">
      <%= link_to "My Account",
                    edit_user_registration_path,
                    method: :get,
                    class: "btn btn--dark" %>
      <%= button_to "Sign out",
                    destroy_user_session_path,
                    method: :delete,
                    class: "btn btn--dark" %>
    </div>
  <% else %>
    <div class="navbar__title">
      <img src="/bookhaven_logo.png" alt="bookhaven" >
    </div>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookhaven</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/navbar" unless current_page?(new_user_session_path) %>
    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/libraries/_library.html.erb
<div class="library">
  <%= link_to library_path(library) do %>
    <div class="library_name">
      <%= library.name %>
    </div>
  <% end %>

  <div class="num_of_books">
    Number of Books: <%= library.num_of_books %>
  </div>
  
  <div class="directions_link">
    <%= link_to "Get Directions", 
                "https://www.google.com/maps/dir/?api=1&destination=#{library.full_address}",
                target: "_blank",
                rel: "noopener noreferrer" %>
  </div>
</div>

app/views/libraries/index.html.erb
<main class="container">
  <div class="add_library">
    <%= link_to "Add an New Library",
                new_library_path, 
                class: 'btn btn--secondary' %>
  </div>
  <div class="libraries">
    <% @libraries.each do |library| %>
      <%= render 'library', library: library %>
    <% end %>
  </div>
</main>

app/views/libraries/new.html.erb
<main class="container">
  <h1>Add a Library</h1>
  <div class="library_form">
    <%= form_with(model: @library, local: true) do |f| %>
      <div class="field">
        <%= f.label :name %>:
        <%= f.text_field :name %>
      </div>
      <br>
      <div class="field">
        <%= f.label :address %>:
        <%= f.text_field :address %>
      </div>
      <br>
      <div class="field">
        <%= f.label :city %>:
        <%= f.text_field :city %>
      </div>
      <br>
      <div class="field">
        <%= f.label :state %>:
         <%= f.collection_select :state, state_options, :first, :last, prompt: 'Select a state' %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Add Library", class: "btn btn--submit" %>
      </div>
    <% end %>
  </div>
</main>

app/views/libraries/show.html.erb
<main class="container">
  <div class="library_details">
    <h1><%= @library.name %></h1>
    <div class="directions_link">
    <%= link_to "Get Directions", 
                "https://www.google.com/maps/dir/?api=1&destination=#{@library.full_address}",
                target: "_blank",
                rel: "noopener noreferrer" %>
  </div>
    <h4>Number of books in this library: <%= @library.num_of_books %></h4>
  </div>
  <div class="add_book">
    <%= link_to "Add a book to this Library", 
                new_book_path(library_id: @library.id), 
                class: 'btn btn--secondary' %>
  </div>
  <br>
  <div class="books">
    <% @library.books.each do |book| %>
      <%= link_to book_path(book) do %>
        <div class="book">
          <h2><%= book.title %></h2>
          <p>By: <%= book.author %></p>
        </div>
      <% end %>
    <% end %>
</main>

app/views/welcome/_welcome_actions.html.erb
<%= link_to "Explore Nearby Free Libraries",
                  libraries_path,
                  method: :get,
                  class: "btn btn--welcome" %>
<%= link_to "Search for Books",
              books_path,
              method: :get,
              class: "btn btn--welcome" %>
<%= link_to "My Bookshelf",
              root_path,
              method: :get,
              class: "btn btn--welcome" %>
<%= link_to "About BookHaven",
              about_path,
              method: :get,
              class: "btn btn--welcome" %>

app/views/welcome/_welcome_description.html.erb
<div class="welcome_description">
  BookHaven brings together book lovers and book sharers. Find a book you want to read, and borrow it from a free local little outdoor library near you.
  Here, you can explore and contribute to the inventory of free little neighborhood libraries all around the us. Stumble upon an little neighborhood 
  library that you don't find on our site? Add it to our database by taking a quick picture of the library and uploading it to our site.
  This space can also be used to keep track of all the books you have read, are currently reading, or want to read. So enjoy being outside and sharing books!
  Sign up or log in to get started!
</div>

app/views/welcome/index.html.erb
<main class="welcome">
  <div class="welcome_title">
    Welcome User!
  </div>
  <div class="welcome_actions">
    <%= render partial: "welcome/welcome_actions" %>
  </div>
  <img class="little_library" src="/library.png" alt="library" >  
  <img src="/grass.png" alt="Grass" class="grass_img" >  
</main>